NCIEVS/evsrestapi

- software/evs-sparql-util/src/gov/nih/nci/sparql/bean/Concept.java
Testing folk and pull request.
> Test folk.

- src/main/java/gov/nih/nci/evs/api/configuration/JacksonConfiguration.java
- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
- src/main/java/gov/nih/nci/evs/api/model/Association.java
- src/main/java/gov/nih/nci/evs/api/model/Concept.java
- src/main/java/gov/nih/nci/evs/api/model/Definition.java
- src/main/java/gov/nih/nci/evs/api/model/Map.java
- src/main/java/gov/nih/nci/evs/api/model/Property.java
- src/main/java/gov/nih/nci/evs/api/model/Relationship.java
- src/main/java/gov/nih/nci/evs/api/model/ResultList.java
- src/main/java/gov/nih/nci/evs/api/model/Role.java
- src/main/java/gov/nih/nci/evs/api/model/Synonym.java
- src/main/java/gov/nih/nci/evs/api/model/Terminology.java
- src/main/java/gov/nih/nci/evs/api/service/QueryBuilderServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/IncludeFlagUtils.java
- src/main/java/gov/nih/nci/evs/api/util/ModelUtils.java
- src/test/java/gov/nih/nci/evs/api/SerializationTester.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
- src/test/java/gov/nih/nci/evs/api/model/AssociationUnitTest.java
- src/test/java/gov/nih/nci/evs/api/model/ConceptUnitTest.java
- src/test/java/gov/nih/nci/evs/api/model/DefinitionUnitTest.java
- src/test/java/gov/nih/nci/evs/api/model/MapUnitTest.java
- src/test/java/gov/nih/nci/evs/api/model/PropertyUnitTest.java
- src/test/java/gov/nih/nci/evs/api/model/RoleUnitTest.java
- src/test/java/gov/nih/nci/evs/api/model/SynonymUnitTest.java
Implement /metadata/{terminology}/.. with tests
> EVSRESTAPI-33

- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/VersionControllerTests.java
Fixes relating to test failures -- metadata controller and version controller
> Version controller and metadata controller test fixes

- build.gradle
- src/main/java/gov/nih/nci/evs/api/service/QueryBuilderServiceImpl.java
- src/main/resources/sparql-queries.properties
A named param can be defined as #{name} -- ${name} already has a special meaning in spring properties. Spring uses $ format to wire environment variables automatically. So, did not want to change spring behavior.
> sparql queries to config file using named parameters

- src/main/java/gov/nih/nci/evs/api/support/SearchCriteriaWithoutTerminology.java
Small fix relating to search controller test failure. Kindly review.
> search controller validation fix

- README.md
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
Fix conceptStatus test
fix Subtree getting top-level concept
typo in readme
> test fix, subtree fix in top level, typo in readme

- src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java
- src/main/java/gov/nih/nci/evs/api/model/HierarchyNode.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
adds siblings of concepts in concept tree of subtree search
> sibling concepts in subtree call

- src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java
- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
Implements the maxLevel parameter in getDescendants. Remaking the PR because of some weird branching issue I had with the previous version
> EVSRESTAPI-117

- src/main/resources/sparql-queries.properties
- pulling in all relevant clauses into role and inverse role queries
> more clauses in role queries

- STARDOG.md
- src/main/java/gov/nih/nci/evs/api/service/QueryBuilderService.java
- src/main/java/gov/nih/nci/evs/api/service/QueryBuilderServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
Better handling of the condition that lead to the associations issue on indexing.  In effect, more reliable failure handling.
> EVSRESTAPI-130

- README.md
- src/main/java/gov/nih/nci/evs/api/service/ElasticLoadServiceImpl.java
I think i got it all but it's probably worth checking to make sure I didn't miss anything
> remove non-Real Time stuff from loadConcepts

- src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryService.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/EVSUtils.java
- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/QualifierTests.java
qualifiers include with labels
fix roots include param
> EVSRESTAPI-121

- src/main/java/gov/nih/nci/evs/api/controller/SearchController.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/RESTUtils.java
- src/main/resources/application-local.yml
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
also expands on concept code search test
> Blank term search

- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
fixes exact match terms not showing first in startsWith searches
> Evsrestapi125

- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
reimplementation of definitions search in general search cases
> partial reimplementation of definition search

- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
fixing synonymTermGroup + synonymSource search
fixing other tests with old concepts
> EVSRESTAPI-136

- src/main/java/gov/nih/nci/evs/api/service/BaseLoaderService.java
- src/main/java/gov/nih/nci/evs/api/service/DirectoryElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticLoadService.java
- src/main/java/gov/nih/nci/evs/api/service/LoaderServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/StardogElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/PushBackReader.java
- src/main/java/gov/nih/nci/evs/api/util/RrfReaders.java
- src/test/java/gov/nih/nci/evs/api/controller/NCIMControllerTests.java
add definitions to ncim creation
fix index switching after a reindex
> Evsrestapi140

- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
fix test in SearchControllerTests
> fix search test

- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
moves child leaf calculation into indexing to speed up subtree calculations
> index leaf nodes for extra search speed

- src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java
- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
- src/main/java/gov/nih/nci/evs/api/model/Concept.java
- src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java
- src/main/java/gov/nih/nci/evs/api/service/DirectoryElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticLoadService.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryService.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/LoaderServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MetadataService.java
- src/main/java/gov/nih/nci/evs/api/service/MetadataServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerService.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/StardogElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/ConceptUtils.java
- src/main/resources/metadata/ncit.json
creates /metadata/{terminology}/subsets and /metadata/{terminology}/subset/{code} calls for subset API
> subset API Mk 1

- src/main/resources/metadata/ncit.json
address https://tracker.nci.nih.gov/browse/EVSRESTAPI-177
> EVSRESTAPI-177

- src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java
address https://tracker.nci.nih.gov/browse/EVSRESTAPI-165
> EVSRESTAPI-165

- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
implements https://tracker.nci.nih.gov/browse/EVSRESTAPI-179. Hard to test the tags param properly since i don't seem to have any terminologies that have monthly/weekly = false but the tests pass at least
> Evsrestapi179

- src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/main/resources/metadata/ncit.json
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
removes unpublished from qualifiers
> Rdfbrowser116

- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
> fix https://tracker.nci.nih.gov/browse/EVSRESTAPI-187

- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
> Evsrestapi187 2

- src/main/java/gov/nih/nci/evs/api/service/MetadataServiceImpl.java
> Rdfbroswer125

- src/main/java/gov/nih/nci/evs/api/model/Concept.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
deboost retired concepts as per https://tracker.nci.nih.gov/browse/EVSRESTAPI-189
> EVSRESTAPI-189

- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-197
> add version tests

- src/main/java/gov/nih/nci/evs/api/util/ConceptUtils.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-239
> fix missing definitions

- src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java
- src/main/java/gov/nih/nci/evs/api/service/MetaSourceElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/HierarchyUtils.java
- src/main/resources/metadata/mdr.json
> RDFBROWSER-218: better manage concept name computation

- src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java
- src/main/resources/metadata/mdr.json
- src/main/resources/metadata/ncit.json
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-254: Add "has hierarchy" info to terminology metadata
> EVSRESTAPI-254

- src/main/java/gov/nih/nci/evs/api/model/Concept.java
- src/main/java/gov/nih/nci/evs/api/service/MetadataServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
https://tracker.nci.nih.gov/browse/RDFBROWSER-277: Links to the FTP site are not showing up on the Subset pages
> FTP site links not showing on Subset pages

- src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java
- src/main/resources/metadata/mdr.json
- src/main/resources/metadata/ncim.json
- src/main/resources/metadata/ncit.json
https://tracker.nci.nih.gov/browse/EVSRESTAPI-259
> add welcomeText and codeLabel to configs

- src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java
- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
- src/main/java/gov/nih/nci/evs/api/model/Property.java
- src/main/java/gov/nih/nci/evs/api/service/MetadataServiceImpl.java
- src/main/resources/metadata/go.html
- src/test/java/gov/nih/nci/evs/api/controller/MDRControllerTests.java
- src/test/java/gov/nih/nci/evs/api/model/TerminologyMetadataUnitTest.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-284
> Evsrestapi 284: Fix swagger unnecessary "required" fields

- src/main/java/gov/nih/nci/evs/api/controller/SearchController.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-267: Extend "subset" parameter in search calls to accept a wildcard to indicate any subset
> support * as subset parameter

- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/ConceptUtils.java
This was actually a backend fix for the data.
> RDFBROWSER-333: Cleanup how roles work to restore for chebi

- src/test/java/gov/nih/nci/evs/api/ConceptSampleTester.java
- src/test/java/gov/nih/nci/evs/api/controller/SampleTest.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-296: Implement sampling tests for "paths"
> Evsrestapi 296

- src/main/java/gov/nih/nci/evs/api/configuration/EVSElasticsearchRestTemplate.java
- src/main/java/gov/nih/nci/evs/api/model/IncludeParam.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/support/es/EVSConceptResultMapper.java
- src/main/java/gov/nih/nci/evs/api/util/ConceptUtils.java
- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-317: getConcepts returns full payload regardless of given parameters
> EVSRESTAPI-317: fix getConcepts ignoring parameters

- src/test/java/gov/nih/nci/evs/api/ConceptSampleTester.java
- src/test/java/gov/nih/nci/evs/api/controller/SampleTest.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-298
> Evsrestapi 298

- src/test/java/gov/nih/nci/evs/api/ConceptSampleTester.java
- src/test/java/gov/nih/nci/evs/api/controller/SampleTest.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-299
> Implement sampling tests for "association entries" - EVSRESTAPI-299

- src/main/java/gov/nih/nci/evs/api/controller/MapsetController.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-345
> EVSRESTAPI-345 - sort mappings by codes

- src/main/java/gov/nih/nci/evs/api/controller/MapsetController.java
https://tracker.nci.nih.gov/browse/RDFBROWSER-379
> RDFBROWSER-379: fix out of memory error

- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
https://tracker.nci.nih.gov/browse/RDFBROWSER-361
> RDFBROWSER-361: search with phrase keyword fixed

- src/main/java/gov/nih/nci/evs/api/controller/SearchController.java
- src/main/java/gov/nih/nci/evs/api/model/IncludeParam.java
- src/main/java/gov/nih/nci/evs/api/model/Map.java
- src/main/java/gov/nih/nci/evs/api/service/AbstractStardogLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MetaElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MetaSourceElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MetadataServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/support/es/ElasticObject.java
- src/test/java/gov/nih/nci/evs/api/ConceptSampleTester.java
- src/test/java/gov/nih/nci/evs/api/controller/ChebiSampleTest.java
- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerIncludeTests.java
- src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/GoSampleTest.java
- src/test/java/gov/nih/nci/evs/api/controller/HgncSampleTest.java
- src/test/java/gov/nih/nci/evs/api/controller/MapsetControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/MdrControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/NcimControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/QualifierTests.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
- src/test/java/gov/nih/nci/evs/api/controller/VersionControllerTests.java
- src/test/java/gov/nih/nci/evs/api/model/MapUnitTest.java
> Test fixes

- src/main/java/gov/nih/nci/evs/api/service/MappingLoaderServiceImpl.java
- src/main/resources/application-local.yml
https://tracker.nci.nih.gov/browse/EVSRESTAPI-380
> Pva/evsrestapi 380 - Handle mapping files from Liz in the 2-column format

- src/main/bin/reindex.sh
- src/main/java/gov/nih/nci/evs/api/controller/SearchController.java
- src/main/java/gov/nih/nci/evs/api/model/SearchCriteriaWithoutTerminology.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-373
You'd mentioned that ncim.sh takes care of some of the terminologies, and it seems to already have a block of code for this.
> Evsrestapi 373 - Reindex should delete and index partially loaded indexes

- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
- src/main/java/gov/nih/nci/evs/api/model/StatisticsEntry.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryService.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MetaElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MetadataService.java
- src/main/java/gov/nih/nci/evs/api/service/MetadataServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/support/es/ElasticObject.java
- src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
> Evsrestapi 352

- src/main/java/gov/nih/nci/evs/api/service/MappingLoaderServiceImpl.java
forgot a bit of backend work for rdf-browser-400
> forgot to actually push some backend stuff

- src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java
- src/main/java/gov/nih/nci/evs/api/service/MetaElasticLoadServiceImpl.java
Remove old snomed indexes properly when adding new ones: https://tracker.nci.nih.gov/browse/EVSRESTAPI-391
> remove old snomed indexes properly

- src/main/java/gov/nih/nci/evs/api/util/HierarchyUtils.java
Fix duplicate parents in OBIB: https://tracker.nci.nih.gov/browse/EVSRESTAPI-442
> fix duplicate parents

- src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java
- src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
Support excluding properties from indexing via config json: https://tracker.nci.nih.gov/browse/EVSRESTAPI-431
> exclude properties

- README.md
- build.gradle
- src/main/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceImpl.java
- src/main/resources/application-local.yml
- src/test/java/gov/nih/nci/evs/api/controller/TermSuggestionFormControllerTests.java
- src/test/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceTest.java
Fixed the annotations on the tests failing in TermSuggestionFormServiceTest that were causing the tests to failing due to the mock being reset.
Updated the google java format (GJF) version in the gradle and updated the code that was causing the github action.
> EVSRESTAPI-463 fix failing tests

- README.md
- build.gradle
- src/main/java/gov/nih/nci/evs/api/controller/TermSuggestionFormController.java
- src/main/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceImpl.java
- src/main/resources/application-local.yml
- src/test/java/gov/nih/nci/evs/api/controller/TermSuggestionFormControllerTests.java
- src/test/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceTest.java
Added @Hidden to the term form controller so the endpoints aren't exposed.
> EVSRESTAPI-472 swagger documemtation fix

- src/main/java/gov/nih/nci/evs/api/controller/ErrorHandlerController.java
- src/main/java/gov/nih/nci/evs/api/controller/SearchController.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java
> EVSRESTAPI-459: fix errors add swagger

- src/main/java/gov/nih/nci/evs/api/controller/TermSuggestionFormController.java
- src/main/java/gov/nih/nci/evs/api/model/EmailDetails.java
- src/main/java/gov/nih/nci/evs/api/service/CaptchaService.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/java/gov/nih/nci/evs/api/controller/TermSuggestionFormControllerTests.java
Updated the mail server props for the Term Suggestion form to use a nih host and port. Updated application.yml and application-local.yml files
Updated term form Controller exception handling to align with the design of other controllers.
> EVSRESTAPI-474: Fix mail server properties

- src/main/java/gov/nih/nci/evs/api/controller/ErrorHandlerController.java
- src/main/java/gov/nih/nci/evs/api/controller/SearchController.java
- src/main/java/gov/nih/nci/evs/api/model/EmailDetails.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/QueryBuilderServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
> EVSRETSAPI-339: Do a better job handling newlines in sparql queries and specifically deal better with sparql queries containing comments

- src/main/java/gov/nih/nci/evs/api/properties/ApplicationProperties.java
- src/main/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceImpl.java
- src/test/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceTest.java
Added the recaptcha site key to the JSON object response for getForm(). Updated the ApplicationProperties.java to contain the recaptchaSiteKey so we can populate the JSON object with a property recaptchaSiteKey. 
Updated tests to check the response has a recaptchaSiteKey
> EVSRESTAPI-462 update recaptcha site key 

- src/main/java/gov/nih/nci/evs/api/controller/TermSuggestionFormController.java
- src/main/java/gov/nih/nci/evs/api/service/CaptchaService.java
- src/main/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceImpl.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/java/gov/nih/nci/evs/api/controller/TermSuggestionFormControllerTests.java
- src/test/java/gov/nih/nci/evs/api/model/EmailDetailsTest.java
- src/test/java/gov/nih/nci/evs/api/service/CaptchaServiceTest.java
- src/test/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceTest.java
- src/test/resources/application-test.yml
- src/test/resources/formSamples/compareEmailDetails.json
- src/test/resources/formSamples/compareEmailDetailsFail.json
Updated the Term Form tests to cover missing paths, increase some line coverage, and fix the Integration Tests for the Term Form.
Upgrading to JUnit5 will allow us to do parameterized testing to increasing line coverage (specifically for EmailDetails.java) but the tests covers all scenarios. 
integrationTestSubmitForm needs the login credentials for mailfwd.nih.gov set for MAIL_USER and MAIL_PASSWORD, otherwise the email can't be sent.
> EVSRESTAPI-464 term form test cov

- src/main/java/gov/nih/nci/evs/api/controller/MapsetController.java
- src/main/java/gov/nih/nci/evs/api/model/ConceptMap.java
- src/main/java/gov/nih/nci/evs/api/service/BaseLoaderService.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchService.java
- src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MappingLoaderServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/service/MetaElasticLoadServiceImpl.java
- src/main/java/gov/nih/nci/evs/api/util/ConceptUtils.java
- src/test/java/gov/nih/nci/evs/api/controller/MapsetControllerTests.java
- src/test/java/gov/nih/nci/evs/api/model/MapUnitTest.java
fixed PR to deal with duplication issue, fixed tests in MapUnit
> sort key in mappings

- src/main/java/gov/nih/nci/evs/api/controller/TermSuggestionFormController.java
- src/main/java/gov/nih/nci/evs/api/model/EmailDetails.java
- src/main/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceImpl.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/java/gov/nih/nci/evs/api/model/EmailDetailsTest.java
- src/test/resources/formSamples/submissionFormWithArrayList.json
Update EmailDetails model to handle generating a formatted body with an ArrayList present in the body to show all options selected in the CDISC form .
Added a test to confirm we are generating an email correctly with array lists present
Tag created and deployed to DEV environment for testing: v2024-07-30-2.0.0.RELEASE
> RDFBROWSER-449 dropdown search

- build.gradle
- src/main/java/gov/nih/nci/evs/api/model/EmailDetails.java
Fixing a typo causing the header tag to appear in the term form email. 
Tag created: v2024-12-17-2.0.0.RELEASE
> RDFBROWSER-522 closed header 2 style tag

- build.gradle
- src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java
https://tracker.nci.nih.gov/browse/RDFBROWSER-552: open terminologies.md link in new tab to avoid github iframe rules
> make swagger links to github open in new tab automatically

- build.gradle
- src/main/java/gov/nih/nci/evs/api/service/AbstractGraphLoadServiceImpl.java
moves subset link to the concept object instead of the subset object
> move subset link to concept object

- build.gradle
https://tracker.nci.nih.gov/browse/EVSRESTAPI-605: update spring boot version
> update spring boot version

- src/main/bin/devreset.sh
- src/test/java/gov/nih/nci/evs/api/controller/MedrtSampleTest.java
Update UnitTestData for MED-RT to use more recent version
tested on my local, UnitTestData and build server changes will happen in tandem with this PR being merged
> Evsrestapi 627 update unittestdata medrt
