src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
String contents from rest API output are being compared in search controller tests. However, looks like a new "timeTaken" field was added to resultList output. This is a "variable" field. So, removing that when comparing strings.
Not sure if this is the best way. Perhaps, the tests are not valid if there are many fields of this nature. Since it's just one field for now, I thought this is ok. Please review.
=> search controller tests fix

src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
Added tests one for checking nodes (based on tests for getDescendants) and another for 404 scenario.
I wanted to add one for empty list, but I could not find a case in which that happens. When I give a junk code, the end point returns the top level list think.
=> test for getSubtree in concept controller

src/main/java/gov/nih/nci/evs/api/configuration/TerminologyCacheLoader.java, src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java, src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java, src/main/java/gov/nih/nci/evs/api/service/MetadataService.java, src/main/java/gov/nih/nci/evs/api/service/MetadataServiceImpl.java, src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerService.java, src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java, src/main/java/gov/nih/nci/evs/api/util/TerminologyUtils.java, src/main/resources/ehcache.xml
@bcarlsenca moved cache in sparql manager service to spring cache. Because of the way spring requires beans to be available for proxy to be invoked, we are unable to do the cache loading in postConstruct. So, moved it to an event listener.
=> spring cache for sparql manager

software/evsrestapi-util/src/gov/nih/nci/evs/restapi/common/Constants.java, src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java, src/main/java/gov/nih/nci/evs/api/controller/SearchController.java, src/main/java/gov/nih/nci/evs/api/model/Concept.java, src/main/java/gov/nih/nci/evs/api/model/Property.java, src/main/java/gov/nih/nci/evs/api/model/Qualifier.java, src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java, src/main/java/gov/nih/nci/evs/api/util/EVSUtils.java, src/test/java/gov/nih/nci/evs/api/controller/QualifierTests.java
1a. Consistency - code/type  (concept and metadata calls)
- code -> use @Field(store=false) - properties, qualifier
- type -> for definitions always show
1b. {codeOrLabel} -> rename this in swagger to {codeOrName}
- find all uses of the word "label" and fix them.
1c. top-level concept call needs to include "version" - this probably
needs to be put into elasticsearch index.
=> EVSRESTAPI-114

.gitignore, src/main/java/gov/nih/nci/evs/api/controller/ConceptController.java, src/main/java/gov/nih/nci/evs/api/service/ElasticQueryService.java, src/main/java/gov/nih/nci/evs/api/service/ElasticQueryServiceImpl.java, src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerService.java, src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java, src/main/java/gov/nih/nci/evs/api/util/ConceptUtils.java, src/main/java/gov/nih/nci/evs/api/util/HierarchyUtils.java, src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java
1. Get rid of HierarchyNode where possible. Still using in subtree and subtree/children
2. Remove functions deprecated by this change
3. remove a HierarchyNode helper function that didn't really serve a purpose
There might still be another commit or two for any cleanup that's necessary but this is the meat and potatoes of it.
=> Evsrestapi115

src/main/java/gov/nih/nci/evs/api/configuration/EVSElasticsearchRestTemplate.java, src/main/java/gov/nih/nci/evs/api/configuration/ElasticConfiguration.java, src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java, src/main/resources/application-local.yml, src/main/resources/application.yml
Includes:
- query logging: elasticsearch honors the query logging property for only some of the query methods, therefore using custom ElasticsearchRestTemplate to log query being sent to elasticsearch
- boosting name field matches: boosting name field matches seems to move exact matching documents to the top
=> improving search precision

src/main/java/gov/nih/nci/evs/api/service/ElasticSearchServiceImpl.java
Elasticsearch query needed a sort field beyond just "score" to break ties consistently across nodes/shards.
=> RDFBROWSER-81

src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java, src/main/java/gov/nih/nci/evs/api/service/QueryBuilderServiceImpl.java, src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java, src/main/resources/metadata/ncit.json, src/main/resources/sparql-queries.properties, src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerExtensionTests.java, src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerIncludeTests.java, src/test/java/gov/nih/nci/evs/api/controller/ConceptControllerTests.java, src/test/java/gov/nih/nci/evs/api/controller/DocumentationPayloadExamplesTests.java, src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerIncludeTests.java, src/test/java/gov/nih/nci/evs/api/controller/NCIMControllerTests.java, src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java, src/test/java/gov/nih/nci/evs/api/controller/VersionControllerTests.java, src/test/java/gov/nih/nci/evs/api/service/SparqlQueryManagerImplTests.java, src/test/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImplTests.java
This solution is very "NCIt" specific - i may make a couple more changes to turn this into config.
=> RDFBROWSER-118: definition/synonym sources calls only return those attached to non-retired concepts.

STARDOG.md
I was having trouble running this, then realized two things.  
The -v should be before each volume
The copy should be into /var/opt/stardog, not var/opt/data
=> Update docker copy command

src/main/java/gov/nih/nci/evs/api/model/Map.java, src/main/java/gov/nih/nci/evs/api/service/AbstractStardogLoadServiceImpl.java, src/main/java/gov/nih/nci/evs/api/service/MappingLoaderServiceImpl.java
EVSRESTAPI-333: https://tracker.nci.nih.gov/browse/EVSRESTAPI-333
Refactor NCIt map loading
mapset metadata transition happens through a third ticket later switching the temp one (mapsetMetadata2) out for the old one that's replaced (to maintain current functionality)
=> move ncit maps to ncit loader

src/main/bin/reindex.sh
The check for only the version is matching versions from other terminologies as we add more. So adding check for previous term as well
=> Adding check for previous term as well

src/main/java/gov/nih/nci/evs/api/controller/SearchController.java, src/main/java/gov/nih/nci/evs/api/model/SearchCriteriaWithoutTerminology.java, src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
Added the content type consumed by the POST api to text/plain. This will now be in the swagger documentation, which will ensure our SDK code generation includes this in the implementation. 
Commented out a validation check that required a term to not be null in the search api. Added a TODO and a Jira ticket was created to fix later. 
Updated Sparql tests to pass content type for search calls.
=> EVSRESTAPI-470 java sdk content type fix

.github/workflows/makefile.yml, src/main/java/gov/nih/nci/evs/api/controller/TermSuggestionFormController.java, src/main/java/gov/nih/nci/evs/api/model/EmailDetails.java, src/main/java/gov/nih/nci/evs/api/service/CaptchaService.java, src/main/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceImpl.java, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/java/gov/nih/nci/evs/api/controller/TermSuggestionFormControllerTests.java, src/test/java/gov/nih/nci/evs/api/model/EmailDetailsTest.java, src/test/java/gov/nih/nci/evs/api/service/CaptchaServiceTest.java, src/test/java/gov/nih/nci/evs/api/service/TermSuggestionFormServiceTest.java, src/test/resources/application-test.yml, src/test/resources/formSamples/compareEmailDetails.json, src/test/resources/formSamples/compareEmailDetailsFail.json, src/test/resources/formSamples/submissionFormTest.json
Updated the EmailDetails model to use HTML encoding to build the email body for a submitted term form. The email is now correctly formatted when being sent
=> EVSRESTAPI-488 html encoding

src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
fixing a test that failed on devreset. opensearch didn't like how expansive the CONTAINS search result was, so i switched it to a STRSTARTS, which still returns the desired result from the search and the test now passes
=> quick fix for test fail

build.gradle
Updated the versions so they align with what `spring-boot-starter-test` is automatically using.
=> HOTFIX for JUnit and testing gradle dependencies

src/main/java/gov/nih/nci/evs/api/controller/SearchController.java, src/main/java/gov/nih/nci/evs/api/service/QueryBuilderService.java, src/main/java/gov/nih/nci/evs/api/service/QueryBuilderServiceImpl.java, src/main/resources/sparql-queries.properties, src/test/java/gov/nih/nci/evs/api/controller/SearchControllerTests.java
This ticket adds an endpoint for returning the prefixes for a particular terminology (as well as tests for that).
It also adds a "prefixes" parameter to the existing calls that take a sparql query and allows the user to set to "true" and then pass queries with prefixes set.  The examples in develop branch of evsrestapi-client-SDK now have (tested) examples of this usage.
=> EVSRESTAPI-491: sparql prefixes improvements

src/main/bin/postman.sh
we don't want indexing to stop if it can't find a content qa for the current terminology
devreset and the like will not work until this is merged
=> shouldn't end devreset if we dont find a collection

build.gradle, src/main/java/gov/nih/nci/evs/api/controller/MetadataController.java, src/test/java/gov/nih/nci/evs/api/controller/MetadataControllerTests.java
added new endpoint to get all the metadata shown in the EVS-Explore overview tab. Makes for fewer calls to the backend in deciding which in the list should be greyed out.
=> add new endpoint for overview in evs-explore

src/main/java/gov/nih/nci/evs/api/model/TerminologyMetadata.java, src/main/java/gov/nih/nci/evs/api/service/LoaderServiceImpl.java
EVSRESTAPI-502: add index runtime to metadata of terminology (in milliseconds)
=> add index runtime to terminology metadata

src/main/java/gov/nih/nci/evs/api/service/SparqlQueryManagerServiceImpl.java
https://tracker.nci.nih.gov/browse/EVSRESTAPI-665: crashing on reindex of mged terminology
fixed by accounting for bindings with null propertyCode
=> fix mged crash on reindex in roles
